### ISSUE TITLE
Title: Add Favicon 

### ISSUE THREAD

**Issue by AnkitMajee** [prathimacode-hub/Dev-Mint#19]
### Are you a JWOC participant?

Yes , I am Ankit Majee JWOC Mentee

### Is your feature request related to a problem? Please describe.

Yes , my feature will give a new look and design into the website 

### Describe the solution you'd like.

Designing a logo which will be displayed on the icon of the website 

### Describe alternatives you've considered.

We can add project icon or will create a brand new one which will fit the project theme .

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/76817118/218323238-4740dd91-719e-4579-ac3d-0440b33e5963.png)
![image](https://user-images.githubusercontent.com/76817118/218323245-72cd7483-86b5-4840-b7fd-ae757748a288.png)

**Comment by AK-shat-JAIN** [comment]
Are you a JWOC participant?
Yes , I am Aksaht Jain JWOC Mentee

Is your feature request related to a problem? Please describe.
Yes , my feature will give a new look and design into the website

Describe the solution you'd like.
Designing a logo which will be displayed on the icon of the website

Describe alternatives you've considered.
We can add project icon or will create a brand new one which will fit the project theme .

Add any other context or screenshots about the feature request here.
Please provide me with favicon to be added

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by Pritam991** [comment]
can i work on this ?

**Comment by Pritam991** [comment]
please assign me in this issue.

**Comment by AK-shat-JAIN** [comment]
Hello @AnkitMajee 
Please respond and assign the task

**Comment by AnkitMajee** [comment]
I'm not the mentor contact https://github.com/prathimacode-hub
@prathimacode-hub

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
