### ISSUE TITLE
Add TIC TAC TOE

### ISSUE THREAD

**Issue by khushimarothi** [prathimacode-hub/Dev-Mint#25]
### Are you a JWOC participant?

My name is Khushi Marothi and I'm contributor in JWOC

### Is your feature request related to a problem? Please describe.

Want to add a TIC TAC TOE game.

### Describe the solution you'd like.

Tech stack: html,css,js

### Describe alternatives you've considered.

NA

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
