### ISSUE TITLE
[PROJECT PROPOSAL] - AI Image Generator

### ISSUE THREAD

**Issue by AaadityaG** [prathimacode-hub/Dev-Mint#26]
## Project Request
AI Image Generator

---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | It is image generating project using the prompt from user and user can also download the generated images |
| Github | aaadityaG              |
| Email  |  helloadig@gmail.com                                 |
| Label  | Project Request                   |

---

**Define You**

- [x] CodePeak 2023 Participant
- [ ] Contributor

# Project Name

AI Image Generator

## Description (Is your feature request related to a problem? Please describe)

I am contributing this project for HTML / CSS / JS Apps section

## Scope (Describe the solution you'd like.)

The project is made with openjourneys api available at hugginface. 
To use this project all we need to type prompt(description the image and hit enter.)

## Video Links or Support Links (if applicable)
https://ai-images-generator-three.vercel.app/

![AI Image Generator - 1](https://github.com/prathimacode-hub/Dev-Mint/assets/114663382/a51d0556-942b-4fdf-aebe-16d96baf62a9)

**Comment by prathimacode-hub** [comment]
Issue assigned to @AaadityaG
