### ISSUE TITLE
Javascript Quiz App

### ISSUE THREAD

**Issue by SattyamSamania** [prathimacode-hub/Dev-Mint#4]
Can I add Javascript Quiz App made with HTML, CSS and JS in the HTML + CSS + JS Apps. If you think that would be helpful kindly assign the issue to me. Thank You!

**Comment by prathimacode-hub** [comment]
Kindly recreate an issue using issue template which was automated now along with the issue details for getting it assigned. This issue is useful. @SattyamSamania

**Comment by SattyamSamania** [comment]
> Kindly recreate an issue using issue template which was automated now along with the issue details for getting it assigned. This issue is useful. @SattyamSamania

@prathimacode-hub sure. Thank you for the suggestion.
